### ISSUE TITLE
Processing 4.0.1 identified as containing virus on Windows 10 and 11

### ISSUE THREAD

**Issue by tomek-** [benfry/processing4#540]
## Description
Windows 10 and 11 security identifies processing-4.0.1-windows-x64.zip as containing a virus and it rejects download ;( 

## Steps to Reproduce
1. Click the download link in any browser on Windows 10 or 11 :( 

## Your Environment
I checked the problem on two separate computers running Windows 10 and 11.

**Comment by saturnation** [comment]
I got the same result. It's reporting that it's detecting

TrojanDownloader:Java/OpenConnection.PM

**Comment by saturnation** [comment]
Also detected in 3.5.4 windows download

**Comment by Herbin45** [comment]
I detected it in version 4.0.1 as well.

**Comment by danzeeeman** [comment]
came here to report that I hit it also..

**Comment by tomek-** [comment]
Fixed as with the latest download on August 24, 2022.
Thnx!

**Comment by benfry** [comment]
Since this issue still shows up in search results, here's a longer explanation to the problem: https://github.com/processing/processing4/wiki/Troubleshooting#viruses-and-trojans
